ext-gmssl:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: gmssl/GmSSL-PHP
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  depends:
    - gmssl
  php-extension:
    arg-type: with-path
