ext-xhprof:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: longxinH/xhprof
      source-root: extension
    metadata:
      license-files: [LICENSE]
      license: Apache-2.0
  depends:
    - ext-ctype
  php-extension:
    os:
      - Linux
      - Darwin
    arg-type: enable
    build-with-php: true
