ext-rar:
  type: php-extension
  artifact:
    source:
      type: ghrel
      repo: cataphract/php-rar
      match: rar-.+\.tgz
      prefer-stable: true
    metadata:
      license-files: [LICENSE]
      license: PHP-3.01
  lang: cpp
