ext-swow:
  type: php-extension
  artifact:
    source:
      type: ghtar
      repo: swow/swow
      prefer-stable: true
      source-root: ext
    metadata:
      license: Apache-2.0
      license-files: [LICENSE]
  suggests:
    - openssl
    - curl
    - ext-openssl
    - ext-curl
    - postgresql
  php-extension:
    arg-type: custom
